version: '3.4'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  ems:
    image: ems:latest
    ports:
      - '9000:9000'
    depends_on:
      - mysql
    environment:
      spring.datasource.url:  jdbc:mysql://mysql:3306/employee?createDatabaseIfNotExist=true