spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/employee?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9000
endpoints:
  autoconfig:
    enabled: false
  endpoints:
    beans:
      enabled: false
    configprops:
      enabled: false
    dump:
      enabled: false
    env:
      enabled: false
      health:
        enabled: true
      info:
        enabled: true
      metrics:
        enabled: false
      mappings:
        enabled: false
      shutdown:
        enabled: false
      trace:
        enabled: false
